repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, perf, deps, revert, docs, style, chore, refactor, test, build, ci]
        # the types after "docs" are hidden from the changelog by default
